local vim = vim
vim.o.tabstop = 2
vim.o.shiftwidth = 2
vim.o.expandtab = true
vim.o.autoindent = true
vim.o.smartindent = true
vim.o.shiftround = true
vim.wo.number = true
vim.o.relativenumber = false
vim.o.pumheight = 10
vim.o.clipboard = "unnamedplus"
vim.opt.termguicolors = true
vim.opt.signcolumn = "no"
